### ISSUE TITLE
ripe-sdk doesn't work with RequireJS

### ISSUE THREAD

**Issue by marcomontalbano** [ripe-tech/ripe-sdk#111]
`ripe-sdk` seems doesn't work on projects that use `RequireJS`.
We are upgrading `ripe-sdk` from `1.2.4` to latest version (`1.6.25`), but we encounter this issue:

<img width="629" alt="ripe-sdk requirejs" src="https://user-images.githubusercontent.com/1681269/63669938-ac0fe980-c7db-11e9-9b13-ba7d1d62b4cc.png">

I notice that between `1.2.4` and latest version the `if` statement has been changed.
I tried putting back the old one
```js
if (typeof window === "undefined" && typeof require !== "undefined") {
  ...
```

and it works.

Could you check this?
Thanks

**Comment by gcandal** [comment]
@marcomontalbano we'll look into it, thanks for reaching out as well as investigating the issue.

**Comment by joamag** [comment]
@marcomontalbano this issue should now be fixed, going to create a new release

**Comment by joamag** [comment]
@marcomontalbano Please try version 1.6.26 and let us know if everything is working.

**Comment by marcomontalbano** [comment]
@joamag I can confirm you that version 1.6.26 is working fine with RequireJS. Thanks!
