### ISSUE TITLE
Static analysis of XMLHttpRequest package import causes problems on `watch`

### ISSUE THREAD

**Issue by BeeMargarida** [ripe-tech/ripe-sdk#202]
## Description

The conditional import of the `xmlhttprequest` package in SDK causes an error:

`ERROR in ../ripe-commons-pluginus/node_modules/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Can't resolve 'child_process' in '/Users/margarida/Documents/ripe-commons-pluginus/node_modules/xmlhttprequest/lib'`.

By bug was introduced in the commit [ebc58a3](https://github.com/ripe-tech/ripe-sdk/commit/ebc58a34c708e6eb0e8ca714416d163fb97a9035), where the import of the `xmlhttprequest` package was directly imported instead of using a variable. With the use of a variable, the problem does not occur, however a warning appears `Critical dependency: the request of a dependency is an expression`. 

Due to this, webpack static analysis may be the cause of the problem.

Similar problems found in the wild: 
https://github.com/asvd/jailed/issues/22
https://github.com/cytoscape/cytoscape.js/issues/998

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | No errors launched when linking to ripe-sdk. |
| **Observed** | Errors linking to more recent versions of ripe-sdk. |

## Repro Steps

1. Run `npm link` and `npm run watch` in ripe-sdk
2. Link ripe-sdk in ripe-commons-pluginus or ripe-sdk-components-vue with the command `npm link ripe-sdk`
3. Link ripe-commons-pluginus to ripe-white or just run ripe-sdk-components-vue.

## Environment

| Key | Value |
| --- | --- |
| **Device** | iMac |
| **Operating System** | MacOS Catalina |
| **Browser** | Firefox |
| **Instance (URL)** | https://localhost:3000 |

## Screens
<img width="742" alt="Screenshot 2020-10-14 at 08 40 21" src="https://user-images.githubusercontent.com/25725586/95958938-be8f1d00-0df9-11eb-97c5-5eba7fe30e9e.png">

**Comment by gcandal** [comment]
@BeeMargarida please apply the same hack that there is on `require`. Should solve it, right?

**Comment by gcandal** [comment]
@BeeMargarida please update this issue's state.

**Comment by joamag** [comment]
Closing this issue as solved
