### ISSUE TITLE
Version should be 1.2.0

### ISSUE THREAD

**Issue by marcomontalbano** [ripe-tech/ripe-sdk#28]
The version property inside `package.json` should be `1.2.0`.

https://github.com/ripe-tech/ripe-sdk/blob/1.2.0/package.json#L3

**Comment by hugo-gomes** [comment]
Fixed with https://github.com/ripe-tech/ripe-sdk/commit/af6746b5b6c34af7cb1b0f0fc1bc46701008c147

**Comment by joamag** [comment]
@marcomontalbano I can confirm that version 1.2.1 is now deployed in unpkg. Thank you for the note.
