### ISSUE TITLE
createAttachmentOrder with meta

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-sdk#282]
## Rationale

The creation of order attachments expects a file and a `meta` dictionary (see https://github.com/ripe-tech/ripe-core/blob/ba23882efa65acb165e924c6f836c6933646604f/src/ripe_core/controllers/api/order.py#L97).

However, the current SDK implementation of the endpoint doesn't support `meta` (see https://github.com/ripe-tech/ripe-sdk/blob/c9e7b8ab715d4339ccaac26fbff734df6718a316/src/js/api/order.js#L201).

## Description

The implementation of the rationale above could probably be similar to:

```javascript
    options = Object.assign(options, {
        url: url,
        method: "POST",
        dataM: {
            file: file,
            meta: JSON.stringify(meta)
        },
        auth: true
    });
```

But unless I'm missing something obvious, ripe-sdk doesn't support strings as values when using a multipart payload `dataM` (see https://github.com/ripe-tech/ripe-sdk/blob/c9e7b8ab715d4339ccaac26fbff734df6718a316/src/js/base/api.js#L1238).

Trying to use them results in `RangeError: offset is out of bounds` because the string is not being encoded, resulting in this:

![image](https://user-images.githubusercontent.com/3048875/121161364-d31a9c80-c844-11eb-8653-fe73ac2eeb52.png)

Related: https://github.com/ripe-tech/ripe-core/pull/4564

**Comment by joamag** [comment]
The suggested implementation does not work... if working with multipart you cannot pass dictionaries

**Comment by gcandal** [comment]
You mean dictionaries as values? I didn't, I used a string.

**Comment by joamag** [comment]
yes, but on the server-side you'll not be able to de-serialize them automatically, so no good to pass JSON.dumps

**Comment by joamag** [comment]
You need to use something like meta in the order POST... and still the multi-part issue with strings (in the SDK) would have to be fixed

**Comment by joamag** [comment]
ok maybe I'm wrong and now we support automatic JSON casting in Appier... Go ahead and try to see what's wrong with the multi-part encoding... But check the appier and yonius implementations and the multipart encoder should be aligned with both

<img width="773" alt="Screenshot 2021-06-08 at 11 40 19" src="https://user-images.githubusercontent.com/25441/121171389-5d1b3300-c84e-11eb-8838-14fd66204208.png">

**Comment by joamag** [comment]
@gcandal let's also create some unit tests to avoid regression for this mixed types multipart situationns

**Comment by gcandal** [comment]
Requires https://github.com/hivesolutions/appier/pull/47
