### ISSUE TITLE
Spec.json Tag to deactivate mask

### ISSUE THREAD

**Issue by dsafonso** [ripe-tech/ripe-sdk#307]
## Rationale

Now we have an option on SDK to deactivate the masks and should be nice have  a tag to be add in the model spec to deactivate it.

## Description

Should be possible add a tag example "no_mask" and when this model is on white the masks are deactivated by default.
example:
![image](https://user-images.githubusercontent.com/24550956/131534283-de8b1ec5-16a3-4c79-a464-b6e7601f3bd9.png)
![image](https://user-images.githubusercontent.com/24550956/131534533-7d40bd80-f9a6-4458-ad2f-8e8fa21ef7b5.png)

**Comment by joamag** [comment]
@gcandal Let's do this it should be pretty easy (or not as the config does not exist since the beginning)
@gcandal please explore ideas

**Comment by dsafonso** [comment]
@gcandal Is missing deployment of SDK to test this

**Comment by dsafonso** [comment]
@BeeMargarida Missing update the documentation with this new tag: https://dev.platforme.com/p/specs/build.md

**Comment by BeeMargarida** [comment]
> @BeeMargarida Missing update the documentation with this new tag: https://dev.platforme.com/p/specs/build.md
On it!

**Comment by dsafonso** [comment]
Test with brand `cariuma` model `oca_low` OK :+1:
