### ISSUE TITLE
API masks with the total image size

### ISSUE THREAD

**Issue by dsafonso** [ripe-tech/ripe-sdk#312]
## Description

When the get the compose on white we receive always the image with 1000x1000, but the masks we receive always with the size we on the build.
Example: brand=dior_tmp & model=book_tote the images are 2000x2000 and we get the mask with this size and the compose with 1000x1000

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Receive the mask 1000x1000. |
| **Observed** | Receive the mask 2000x2000. |

## Repro Steps

1. Open, ripe-white-sbx https://ripe-white-sbx.platforme.com/?brand=dior_tmp&model=book_tote
2. Open the inspect/ Network and choose images
3. Refresh the page and see the requests mask and compose 
4. if you compare the masks images with the compose images you will see that have different sizes 

## Environment

| Key | Value |
| --- | --- |
| **Device** | Desktop |
| **Operating System** | Ubuntu 21.04 |
| **Browser** | Chrome |
| **Instance (URL)** | https://ripe-core-sbx.platforme.com/api/mask?brand=dior_tmp&frame=side-0&model=book_tote |

## Screens
API Mask request:
https://ripe-core-sbx.platforme.com/api/mask?brand=dior_tmp&frame=side-0&model=book_tote
API Compose request:
https://ripe-core-sbx.platforme.com/api/compose?brand=dior_tmp&debug=1&format=webp&frame=side-0&height=1000&model=book_tote&p=body%3Amesh_logo_mizza_dr%3Amizza&p=handle%3Amesh_logo_handle_mizza_dr%3Amizza&p=ribbon%3Across_stich_mizza_dr%3Amizza&p=shadow%3Adefault%3Adefault&width=1000

![image](https://user-images.githubusercontent.com/24550956/133991363-7bdada26-dc8c-4ffb-9e25-42a95511f2ee.png)

**Comment by gcandal** [comment]
Server-side: enhance the masks endpoint to be able to handle `size`
Client-side: start using the new `size` parameter

**Comment by BeeMargarida** [comment]
@dsafonso Ready to be tested

**Comment by dsafonso** [comment]
Test OK :+1: 
https://ripe-core-now.platforme.com/api/mask?brand=dior_tmp&frame=side-15&model=book_tote&size=720
