### ISSUE TITLE
SDK slow response when doing setInitialsExtra

### ISSUE THREAD

**Issue by 3rdvision** [ripe-tech/ripe-sdk#357]
## Description

SDK takes too long to update images when calling for several `setInitialsExtra`.

In practice ripe-white takes much longer - more than 2x the amount of time - than RIPE API to render an image after user initials requests.

I believe this has to do with SDK's implementation to cancel old requests - it's not working as expected. 

Please watch the videos below.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The image should render what it's typed on white right away, not the first character and then the whole word.  |
| **Observed** | The observed state at the end of the repro steps. |

## Repro Steps

1. Open ripe-white https://ripe-white-now.platforme.com/?context=saint_laurent_hoodie
2. Write something in initials input with more than 1 character like "1234"
2. Watch the image first render an image with the first character "1" and only then "1234" no matter how fast it's typed

### From RIPE White

https://user-images.githubusercontent.com/24736423/154675074-28cfaf4d-8b71-4693-a583-aaf27e82d030.mp4

### From YSL's Website

https://user-images.githubusercontent.com/24736423/154671733-9ef37962-0f57-49fe-8a61-95b511df74c7.mp4

**Comment by 3rdvision** [comment]
This can be solved by implementing a debouncer when doing `setInitialsExtra`.

Now this debouncer could be implemented at SDK level and enabled/disabled with a certain timer by default or we just don't implement it and instead pass that responsibility to whoever uses the SDK.

@joamag  I'd say this is a point of discussion in tech decision.

**Comment by joamag** [comment]
> discussion

Yes, let's implement it at the SDK level. On top of that let's canceled previous requests when new ones arise, if needed.

**Comment by 3rdvision** [comment]
> On top of that let's canceled previous requests when new ones arise, if needed.

That one is [already implemented](https://github.com/ripe-tech/ripe-sdk/blob/master/src/js/base/ripe.js#L1368)

Ok, going ahead with the debouncer implementation at SDK level for the `setInitialsExtra`.

**Comment by luisamd** [comment]
@3rdvision Is this story ready for QA? If so, please update the Kanban board 😄

**Comment by 3rdvision** [comment]
@msp-platforme Deployed and ready to test at https://ripe-white-now.platforme.com/?context=saint_laurent_hoodie

**Comment by msp-platforme** [comment]
We no longer see the first character being rendered first, and then rendering the rest of the inserted characters.
In that regard, the expectation is met.
Speed performance still is not ideal, @3rdvision will see what else can be done.


https://user-images.githubusercontent.com/72499843/159557140-09699a01-e612-40f1-90f3-8f636e8d50bd.mp4
