### ISSUE TITLE
Method for order image URL

### ISSUE THREAD

**Issue by NFSS10** [ripe-tech/ripe-sdk#380]
## Rationale

As there isn't a method in ripe-sdk to get the order image URL so currenlty we manually build the order image URL. Examples: [ripe-pulse](https://github.com/ripe-tech/ripe-pulse/blob/a4eadefdabc2c9d7686b44fe97b1c12b3f7d0328/vue/mixins/domain.js#L340), [ripe-robin-revamp](https://github.com/ripe-tech/ripe-robin-revamp/blob/c75365db6e2a01d86076377f7d8548f0b270d1ed/components/order-detail/chat-order.js#L87), [ripe-util-vue](https://github.com/ripe-tech/ripe-util-vue/blob/e413bf2a378ee26e6eadfedb03569bdca2b8baea/mixins/ripe.js#L99), [ripe-copper](https://github.com/ripe-tech/ripe-copper/blob/61fcf606205daba18c770e5c525684e8514d0428/vue/components/order/order-search/order-search.vue#L268), etc

Having a method to handle this will make the situation less error prone and ensure that compatiblity is maintained everywhere.

## Description

Add a method in ripe-sdk to build and return an order image URL.

## Implementation

Add a method called `_getOrderImageURL` [here](https://github.com/ripe-tech/ripe-sdk/blob/b41bb5d5d531c76f49451cab599e0461400a5abc/src/js/api/order.js#L2152). The approach would be similar to, for example, [_getOrderReportPNGURL ](https://github.com/ripe-tech/ripe-sdk/blob/b41bb5d5d531c76f49451cab599e0461400a5abc/src/js/api/order.js#L2143)

## Reference

https://github.com/ripe-tech/ripe-core/issues/4712 was created because inconsistencies were found between order image URL for build and buildless types.

## Estimation

| Discipline | Estimation |
| --- | --- |
| **Software Development** | 0.5 days |

**Comment by dsafonso** [comment]
Test OK :+1:
