### ISSUE TITLE
Report URLs methods not accepting params

### ISSUE THREAD

**Issue by NFSS10** [ripe-tech/ripe-sdk#381]
## Description

The methods `_getOrderReportURL`, `_getOrderReportPDFURL` and `_getOrderReportPNGURL` aren't correctly handling `params` as they are being ignored and not properly added to the URL.
The methods sould be fixed and the tests updated to catch those cases.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Calling `_getOrderReportPNGURL(1234, "secret-key", { params: { size: 100 } });` should return `orders/1234/report.png?key=secret-key&size=100` |
| **Observed** | Calling `_getOrderReportPNGURL(1234, "secret-key", { params: { size: 100 } });` returns `orders/1234/report.png?key=secret-key` |

## Repro Steps

1. Use one of those methods with `params` passed to `options`
2. Check that the `params` are ignored

## Environment

| Key | Value |
| --- | --- |
| **Device** | Any |
| **Operating System** | Any |
| **Browser** | Any |

**Comment by dsafonso** [comment]
Test OK :+1: 
![image](https://user-images.githubusercontent.com/24550956/160849379-eb4b0451-45dd-48dd-80c3-705f686d5613.png)
