### ISSUE TITLE
Client-Side Rendering (CSR)

### ISSUE THREAD

**Issue by joao-conde** [ripe-tech/ripe-sdk#429]
## Sponsors

- João Magalhães - <joao@platforme.com>
- João Conde - <jc@platforme.com>
- Nuno Silva - <ns@platforme.com>

## Rationale

Pre-Render & Compose (PRC) offers maximum quality but low interactivity for customers. Client-Side Rendering allows for maximum interactivity at the cost of some quality. Additionally, CSR is critical in order to provide state-of-the-art rendering strategies.

We're aiming at using this new CSR approach as a tool to strengthen our relationship with our biggest client (Dior).

## Description

Extend RIPE SDK to provide a real 3D configurator making use of WebGL technology and using our 3DBs as data source.

### Software development

- Define a spec for the 3D information to be stored in the 3DB
- Extend RIPE SDK with a new configurator
- Implement the current SDK API, and extend if need be

## Estimation

| Discipline | Estimation |
| --- | --- |
| **Software Development** | 60 days |

**Comment by NFSS10** [comment]
@hugo-gomes This issue is paused because the PRs are opened for some weeks now. If you take some time to do the final approval and merge them that would be great!

**Comment by hugo-gomes** [comment]
@NFSS10 let's schedule a meeting to discuss those https://calendly.com/d/xz5-ngz-378/client-side-rendering-csr-429

**Comment by joao-conde** [comment]
Believe this can be closed as CSR is not going to be done for RIPE SDK and instead a bespoke solution for Realtime.
