### ISSUE TITLE
No masks options disable highlighting but masks are still loaded

### ISSUE THREAD

**Issue by joao-conde** [ripe-tech/ripe-sdk#446]
## Description

Through the use of `noMasks` or `useMasks` one can control whether the masks are used. However, even when not using them, the SDK still loads them and these represent a significant amount of network requests. We should not load masks if they are not going to be used.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The masks are show and not loaded i.e. no network requests for masks are made. |
| **Observed** | The masks are not shown but are loaded and you can see it in the network requests. |

## Repro Steps

1. Initialize our RIPE in this repo
2. Set `useMasks: false` or `noMasks: true` in the `bindConfigurator` method
3. Build the SDK, launch the demo, go to localhost:8080/simple network tab

## Screens

![image](https://user-images.githubusercontent.com/16060539/203329650-c1841c45-78d2-426c-b2a3-2b07d809e32d.png)

**Comment by msp-platforme** [comment]
:+1: 
When masks are on (parameter use_masks=1) we see a lot of network requests and we can also hover the model and see the masks.
![image](https://user-images.githubusercontent.com/72499843/204344707-79161e03-29f0-488f-ace8-d60e8a1a1d5d.png)

When masks are off (parameter use_masks=0) we don't see network requests related to maks and we if we hover the model it does not have masks.
![image](https://user-images.githubusercontent.com/72499843/204344907-baf932ab-e532-448e-95a6-ae0ee01c2459.png)
